# Generated by Django 3.2.6 on 2021-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категорию в Price List',
                'verbose_name_plural': 'Категории в Price List',
            },
        ),
        migrations.CreateModel(
            name='PriceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Услуга')),
                ('price', models.CharField(max_length=11, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услугу в Price List',
                'verbose_name_plural': 'Услуги в Price List',
            },
        ),
    ]
