# Generated by Django 3.2.6 on 2021-08-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_alter_pricesubcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricecategory',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pricesubcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='title_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Название (РУС)'),
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='title_uz',
            field=models.CharField(default='', max_length=300, verbose_name='Название (УЗБ)'),
        ),
        migrations.AddField(
            model_name='pricesubcategory',
            name='title_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Услуга (РУС)'),
        ),
        migrations.AddField(
            model_name='pricesubcategory',
            name='title_uz',
            field=models.CharField(default='', max_length=300, verbose_name='Услуга (УЗБ)'),
        ),
    ]
