# Generated by Django 3.2.6 on 2021-08-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_metatags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='number',
        ),
        migrations.AddField(
            model_name='addresses',
            name='address_ru',
            field=models.TextField(default='', verbose_name='Адрес (Рус)'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='address_uz',
            field=models.TextField(default='', verbose_name='Адрес (Узб)'),
        ),
        migrations.AddField(
            model_name='emails',
            name='email_ru',
            field=models.CharField(default='', max_length=100, verbose_name='Почта (Рус)'),
        ),
        migrations.AddField(
            model_name='emails',
            name='email_uz',
            field=models.CharField(default='', max_length=100, verbose_name='Почта (Узб)'),
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='number_ru',
            field=models.CharField(default='', max_length=18, verbose_name='Номер (Рус)'),
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='number_uz',
            field=models.CharField(default='', max_length=18, verbose_name='Номер (Узб)'),
        ),
    ]
