# Generated by Django 3.2.6 on 2021-08-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210824_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='address_ru',
            field=models.TextField(verbose_name='Адрес (Рус)'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address_uz',
            field=models.TextField(verbose_name='Адрес (Узб)'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='email_ru',
            field=models.CharField(max_length=100, verbose_name='Почта (Рус)'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='email_uz',
            field=models.CharField(max_length=100, verbose_name='Почта (Узб)'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='number_ru',
            field=models.CharField(max_length=18, verbose_name='Номер (Рус)'),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='number_uz',
            field=models.CharField(max_length=18, verbose_name='Номер (Узб)'),
        ),
    ]
