# Generated by Django 3.2.6 on 2021-08-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210824_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='address_ru',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='emails',
            old_name='email_ru',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='phonenumbers',
            old_name='number_ru',
            new_name='number',
        ),
    ]
