# Generated by Django 3.2.6 on 2021-08-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20210824_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='email_uz',
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='number_uz',
        ),
    ]
