# Generated by Django 3.2.6 on 2021-08-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gynecology', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UziItem',
            new_name='GynecologyItem',
        ),
        migrations.AlterModelOptions(
            name='gynecologyitem',
            options={'verbose_name': 'Вид гинекологических исследований', 'verbose_name_plural': 'Виды гинекологических исследований'},
        ),
    ]
