# Generated by Django 3.2.6 on 2021-08-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labitem',
            options={'verbose_name': 'Вид лаборатоных исследований', 'verbose_name_plural': 'Виды лаборатоных исследований'},
        ),
    ]
