# Generated by Django 3.2.6 on 2021-08-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endocrinology', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UziItem',
            new_name='EndocrinologyItem',
        ),
        migrations.AlterModelOptions(
            name='endocrinologyitem',
            options={'verbose_name': 'Вид эндокринологических исследований', 'verbose_name_plural': 'Виды эндокринологических исследований'},
        ),
    ]
