# Generated by Django 3.2.6 on 2021-08-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UziItem',
            new_name='XRayItem',
        ),
    ]
