# Generated by Django 3.2.6 on 2021-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0003_auto_20210817_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayitem',
            name='banner',
            field=models.ImageField(default=None, upload_to='media', verbose_name='Картинка'),
        ),
    ]
