# Generated by Django 3.2.6 on 2021-08-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0004_xrayitem_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrayitem',
            name='banner',
            field=models.ImageField(upload_to='media', verbose_name='Картинка'),
        ),
    ]
