# Generated by Django 3.2.6 on 2021-08-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardiologyitem',
            options={'verbose_name': 'Вид кардиологических исследований', 'verbose_name_plural': 'Виды кардиологических исследований'},
        ),
    ]
