# Generated by Django 3.2.6 on 2021-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('photo', models.ImageField(upload_to='media', verbose_name='Фотография')),
                ('work_time', models.CharField(max_length=300, verbose_name='Время приёма')),
                ('description', models.TextField(verbose_name='Образование и опыт работы')),
            ],
            options={
                'verbose_name': 'Врача',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
