# Generated by Django 3.2.6 on 2021-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='work_time',
        ),
        migrations.AddField(
            model_name='doctors',
            name='description_ru',
            field=models.TextField(default='', verbose_name='Образование и опыт работы (РУС)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='description_uz',
            field=models.TextField(default='', verbose_name='Образование и опыт работы (УЗБ)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='name_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Имя (РУС)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='name_uz',
            field=models.CharField(default='', max_length=300, verbose_name='Имя (УЗБ)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='photo_ru',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фотография (РУС)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='photo_uz',
            field=models.ImageField(default='', upload_to='media', verbose_name='Фотография (УЗБ)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='slug',
            field=models.CharField(blank=True, max_length=300, unique=True, verbose_name='URL (Необязательно)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Специальность (РУС)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialty_uz',
            field=models.CharField(default='', max_length=200, verbose_name='Специальность (УЗБ)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_time_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Время приёма (РУС)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_time_uz',
            field=models.CharField(default='', max_length=300, verbose_name='Время приёма (УЗБ)'),
        ),
    ]
