# Generated by Django 3.2.6 on 2021-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210816_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='description_ru',
            field=models.TextField(verbose_name='Образование и опыт работы (РУС)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='description_uz',
            field=models.TextField(verbose_name='Образование и опыт работы (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name_ru',
            field=models.CharField(max_length=300, verbose_name='Имя (РУС)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name_uz',
            field=models.CharField(max_length=300, verbose_name='Имя (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='photo_ru',
            field=models.ImageField(upload_to='media', verbose_name='Фотография (РУС)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='photo_uz',
            field=models.ImageField(upload_to='media', verbose_name='Фотография (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialty_ru',
            field=models.CharField(max_length=200, verbose_name='Специальность (РУС)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='specialty_uz',
            field=models.CharField(max_length=200, verbose_name='Специальность (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_time_ru',
            field=models.CharField(max_length=300, verbose_name='Время приёма (РУС)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_time_uz',
            field=models.CharField(max_length=300, verbose_name='Время приёма (УЗБ)'),
        ),
    ]
