# Generated by Django 3.2.6 on 2021-08-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20210816_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='photo_ru',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='photo_uz',
        ),
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(default=None, upload_to='media', verbose_name='Фотография'),
        ),
    ]
