# Generated by Django 3.2.6 on 2021-08-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20210816_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='Фотография'),
        ),
    ]
