# Generated by Django 3.2.6 on 2021-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctors_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='work_time_ru',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='work_time_uz',
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_days_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Дни приёма (РУС)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_days_uz',
            field=models.CharField(default='', max_length=300, verbose_name='Дни приёма (УЗБ)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_from_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Начало приёма (РУС)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_from_uz',
            field=models.CharField(default='', max_length=300, verbose_name='Начало приёма (УЗБ)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_to_ru',
            field=models.CharField(default='', max_length=300, verbose_name='Конец смены (РУС)'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='work_to_uz',
            field=models.CharField(default='', max_length=300, verbose_name='Конец смены (УЗБ)'),
        ),
    ]
