# Generated by Django 3.2.6 on 2021-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20210817_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='work_days_ru',
            field=models.CharField(max_length=300, verbose_name='Дни приёма (РУС)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_days_uz',
            field=models.CharField(max_length=300, verbose_name='Дни приёма (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_from_ru',
            field=models.CharField(max_length=300, verbose_name='Начало приёма (РУС)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_from_uz',
            field=models.CharField(max_length=300, verbose_name='Начало приёма (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_to_ru',
            field=models.CharField(max_length=300, verbose_name='Конец смены (РУС)'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_to_uz',
            field=models.CharField(max_length=300, verbose_name='Конец смены (УЗБ)'),
        ),
    ]
