# Generated by Django 3.2.6 on 2021-08-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20210817_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='work_from_uz',
            new_name='work_from',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='work_to_uz',
            new_name='work_to',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='work_from_ru',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='work_to_ru',
        ),
    ]
