# Generated by Django 3.2.6 on 2021-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_auto_20210817_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='work_from',
            field=models.CharField(max_length=300, verbose_name='Начало приёма'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='work_to',
            field=models.CharField(max_length=300, verbose_name='Конец смены'),
        ),
    ]
